package at.gnu.adventofcode.year2025

import org.junit.Assert.assertEquals
import org.junit.Test
import kotlin.time.measureTimedValue

class Day07Test {

    private val manifold = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent().split("\n")

    private val test = mapOf(
        Day07::part1 to 21L,
        Day07::part2 to 40L
    )

    @Test
    fun testMySolution() {
        for (function in test.keys) {
            val (result, time) = measureTimedValue { function(Day07(manifold)) }
            println("Day07::${function.name}: ${manifold.size} entries -> $result [$time]")
            assertEquals(test[function], result)
        }
    }
}
